version: '3'
services:

  tst_app_nginx:
    container_name: tst_app_nginx
    image: nginx:latest
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tst-network
    depends_on:
      - tst_app_fpm
    volumes:
      - ./:/var/www:ro
      - ./dockerfiles/tst_app_nginx/default.conf:/etc/nginx/conf.d/default.conf

  tst_app_fpm:
    container_name: tst_app_fpm
    working_dir: /var/www    
    build:
      context: .
      dockerfile: dockerfiles/tst_app_fpm/Dockerfile
    networks:
      - tst-network
    extra_hosts:
      - "host.docker.internal:172.110.0.1"
    volumes:
      - ./:/var/www
      - ./storage/logs:/var/log


  tst_mariadb:
    container_name: tst_mariadb
    image: mariadb:10.5
    networks:
      - tst-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.tst_mariadb:/var/lib/mysql

  tst_node:
    container_name: tst_node
    image: node:12
    working_dir: /var/www
    volumes:
      - ./:/var/www


networks:
  default:
  tst-network:
    ipam:
      driver: default
      config:
        - subnet: 172.155.0.0/16
